// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znwevuggtauflfkmzhln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpud2V2dWdndGF1Zmxma216aGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1ODI4MzAsImV4cCI6MjA3NTE1ODgzMH0.zmv5wJ8U6SvfhFwv8rq5ytM_o9ExVBuMYFpqojZw9As";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});